version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace: 
            at: .
      - run:
          name: 'Install Dependecies'
          command: npm install
      - run:
            name: 'Deploy to Hosting'
            command: npx firebase deploy
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

